config/routes.rb
Rails.application.routes.draw do
  resources :card_decks
  resources :games
  resources :card_sets
  resources :cards
  resources :users

  get 'new_game' => 'games#new_game'
  post 'games/player_method' => 'games#player_method'
end

app/controllers/card_sets_controller.rb
class CardSetsController < ApplicationController
  before_action :set_card_set, only: [:show, :edit, :update, :destroy]

  # GET /card_sets
  # GET /card_sets.json
  def index
    @card_sets = CardSet.all
  end

  # GET /card_sets/1
  # GET /card_sets/1.json
  def show
  end

  # GET /card_sets/new
  def new
    @card_set = CardSet.new
  end

  # GET /card_sets/1/edit
  def edit
  end

  # POST /card_sets
  # POST /card_sets.json
  def create
    @card_set = CardSet.new(card_set_params)

    respond_to do |format|
      if @card_set.save
        format.html { redirect_to @card_set, notice: 'Card set was successfully created.' }
        format.json { render :show, status: :created, location: @card_set }
      else
        format.html { render :new }
        format.json { render json: @card_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_sets/1
  # PATCH/PUT /card_sets/1.json
  def update
    respond_to do |format|
      if @card_set.update(card_set_params)
        format.html { redirect_to @card_set, notice: 'Card set was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_set }
      else
        format.html { render :edit }
        format.json { render json: @card_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_sets/1
  # DELETE /card_sets/1.json
  def destroy
    @card_set.destroy
    respond_to do |format|
      format.html { redirect_to card_sets_url, notice: 'Card set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_set
      @card_set = CardSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_set_params
      params.fetch(:card_set, {})
    end
end

app/helpers/card_sets_helper.rb
module CardSetsHelper
end

app/views/card_sets/_form.html.erb
<%= form_for(@card_set) do |f| %>
  <% if @card_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card_set.errors.count, "error") %> prohibited this card_set from being saved:</h2>

      <ul>
      <% @card_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/card_sets/edit.html.erb
<h1>Editing Card Set</h1>

<%= render 'form' %>

<%= link_to 'Show', @card_set %> |
<%= link_to 'Back', card_sets_path %>

app/views/card_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Card Sets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @card_sets.each do |card_set| %>
      <tr>
        <td><%= link_to 'Show', card_set %></td>
        <td><%= link_to 'Edit', edit_card_set_path(card_set) %></td>
        <td><%= link_to 'Destroy', card_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card set', new_card_set_path %>

app/views/card_sets/new.html.erb
<h1>New Card Set</h1>

<%= render 'form' %>

<%= link_to 'Back', card_sets_path %>

app/views/card_sets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_card_set_path(@card_set) %> |
<%= link_to 'Back', card_sets_path %>