config/routes.rb
Rails.application.routes.draw do
  resources :card_decks
  resources :games
  resources :card_sets
  resources :cards
  resources :users

  get 'new_game' => 'games#new_game'
  post 'games/player_method' => 'games#player_method'
end

app/models/game.rb
class Game < ActiveRecord::Base

	include UtilityMethods

	belongs_to :dealer, foreign_key: "dealer_id", :class_name => 'User', autosave: true
	belongs_to :player, foreign_key: "player_id", :class_name => 'User', autosave: true

	has_and_belongs_to_many :card_decks

	attr_accessor :winner

	attr_accessible :dealer_id, :player_id

	after_initialize :initialize_components	

	accepts_nested_attributes_for :dealer, :player

	def initialize_components(card_decks=6)
		initialize_new_card_decks card_decks
		#initialize_players
		@infinity = (1.0/0.0)
		@logger = Logger.new(STDOUT)
		@logger.level = 1
	end

	# call this method to start the game after initializing
	def play
		deal_first_cards
		print_player_details self

		# hit the player and let the fun begin
		#winner = hit

		# print player score when the game ends
		# print_player_details self
		# @logger.info winner.name + " has won the game with " + winner.score.to_s + ' points'
	end

	# initialize system and player
	def initialize_players
		self.dealer = create_new_player 'System', User.roles[:dealer]
		self.player = create_new_player 'Player1'
	end
	
	# initialize the card decks for game. 
	def initialize_new_card_decks(decks)
		self.card_decks ||= []
		for deck in 1..decks
			self.card_decks << CardDeck.new
		end
	end

	# deal the first two cards to dealer and player each
	def deal_first_cards
		deal self.dealer
		deal self.player
	end

	# hit the player and follow the game logic
	# if player score is 21 -  player wins
	# if player score is greater than 21 - dealer wins
	# if player score is less than 20 - ask the player what he wants to do: Hit or Stand

	def hit
		deal self.player
		case self.player.score
		when  21
			return self.player
		when 21..@infinity
			return self.dealer
		when 1..20
			return nil
		end
	end

	# when the player chooses - stand
	# deal card to dealer and check the score
	# if dealer score is 21 - dealer wins
	# if dealer score is greater than 21 - player wins
	# if dealer score is less than 17 - deal another card to dealer and check the score again for the cases
	# if dealer score is between 17 and 20, whoever has greater score, wins the game.
	def stand
		deal self.dealer
		case self.dealer.score
		when  21
			return self.dealer
		when 21..@infinity
			return self.player
		when 1..16
			print_player_details self
			stand
		when 17..20
			# TODO ask what happens when they are equal. For now player wins in case of equal
			return (self.player.score > self.dealer.score ? self.player : self.dealer)
		end
	end

	# find remaining cards
	def remaining_cards
		self.card_decks.inject([]){|cards,deck| cards |= deck.remaining_deck_cards}
	end

	def get_random_card
		card = self.card_decks.select{|deck| deck.remaining_deck_cards.count > 0 }.sample.get_random_card_from_deck
	end

	def deal player
		player.add_card get_random_card
		player.save
		@logger.info "Dealt a card to " + player.name
		@logger.debug 'remaining cards are ' + remaining_cards.count.to_s
		@logger.info ''
	end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
    
  end

  def new_game
    @dealer = User.create( { :name => 'System'})
    @player = User.create( { :name => 'Player1'})
    @game = Game.new({:player_id => @player.id, :dealer_id => @dealer.id})
    @game.play
    @game.winner = @game.hit
    @game.save
    @game_json = @game.as_json(:methods => :winner ,:include => { :card_decks => {
                            :include => { :cards => { :methods => [:suit, :denomination, :suit_cd, :denomination_cd, :symbol], :only => :body } },
                             :only => :title }, :dealer => { :include => {:cards => { :methods => [:suit, :denomination, :suit_cd, :denomination_cd, :symbol], :only => :body } }, :methods => :score },
                             :player => { :include => {:cards => { :methods => [:suit, :denomination, :suit_cd, :denomination_cd, :symbol], :only => :body } }, :methods => :score}  })
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def player_method
    game = Game.find params[:id]
    method = params[:method]
    game.winner = game.send(method.to_sym)
    # game.save
    game_json = game.as_json(:methods => :winner ,:include => { :card_decks => {
                            :include => { :cards => { :methods => [:suit, :denomination, :suit_cd, :denomination_cd, :symbol], :only => :body } },
                             :only => :title }, :dealer => { :include => {:cards => { :methods => [:suit, :denomination, :suit_cd, :denomination_cd, :symbol], :only => :body } }, :methods => :score },
                             :player => { :include => {:cards => { :methods => [:suit, :denomination, :suit_cd, :denomination_cd, :symbol], :only => :body } }, :methods => :score}  })
    respond_to do |format|
      format.json { render json: game_json.to_json , status: 200 }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:dealer_id, :player_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dealer_id %><br>
    <%= f.number_field :dealer_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Dealer</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.dealer_id %></td>
        <td><%= game.player_id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new_game.html.erb
<div class='container game-outer dev-game-outer'>
	<h1>Black Jack</h1>
	<div class='row outer_row'>
		<div class='col-md-12'>
			<div class= 'row player-rows dev-players'>
			</div>
			<div class='dev-status'> </div>
			<div class='row buttons_row dev-buttons'>
				<div class='btn-group'>
					<div class='btn btn-primary dev-hit-button pull-left' data-method='hit'>Hit</div>
					<div class='btn btn-warning dev-stand-button pull-right' data-method='stand'>Stand</div>
				</div>
			</div>
			<div class='btn btn-danger dev-reset-button'>Reset Game</div>
		</div>
	</div>
</div>

<script type="text/javascript">
  $(function() {
    window.router = new BlackJack.Routers.GamesRouter({
    	game: <%= @game_json.to_json.html_safe -%>,
    	card_decks: <%= @card_decks.to_json.html_safe -%>
    });
    Backbone.history.start();
  });
</script>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dealer:</strong>
  <%= @game.dealer_id %>
</p>

<p>
  <strong>Player:</strong>
  <%= @game.player_id %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>