config/routes.rb
Rails.application.routes.draw do
  resources :card_decks
  resources :games
  resources :card_sets
  resources :cards
  resources :users

  get 'new_game' => 'games#new_game'
  post 'games/player_method' => 'games#player_method'
end

app/models/card.rb
class Card < ActiveRecord::Base
	attr_accessor :dealt

	belongs_to :user
	belongs_to :card_deck

	attr_accessible :suit_cd, :denomination_cd, :dealt

	@@suit_symbols = {'spades' => '♠' ,'hearts' =>	'♥', 'diamonds' =>	'♦',	'clubs' => '♠'}

	as_enum :denomination, 'A': 11, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10, 'J': 10, 'Q': 10, 'K': 10
	as_enum :suit, diamonds: 1, clubs: 2, hearts: 3, spades: 4

	def mark_as_dealt
		self.dealt = true
		self.save
	end

	def symbol
		@@suit_symbols[self.suit.to_s]
	end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:suit_cd, :denomination_cd, :card_set_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :suit_cd %><br>
    <%= f.number_field :suit_cd %>
  </div>
  <div class="field">
    <%= f.label :denomination_cd %><br>
    <%= f.number_field :denomination_cd %>
  </div>
  <div class="field">
    <%= f.label :card_set_id %><br>
    <%= f.number_field :card_set_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>

<table>
  <thead>
    <tr>
      <th>Suit cd</th>
      <th>Denomination cd</th>
      <th>Card set</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.suit_cd %></td>
        <td><%= card.denomination_cd %></td>
        <td><%= card.card_set_id %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Suit cd:</strong>
  <%= @card.suit_cd %>
</p>

<p>
  <strong>Denomination cd:</strong>
  <%= @card.denomination_cd %>
</p>

<p>
  <strong>Card set:</strong>
  <%= @card.card_set_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>